### ISSUE TITLE
Plugin niet getest met laatste versie (4.9.1)

### ISSUE THREAD

**Issue by MWeesenaar** [mdeheij/hostnet-mailer#4]
Hi,

Allereerst; thanks voor de prettige plugin! :)
Ik wil de plugin updaten, van 1.40 naar 3.3 (lijkt een vrij grote stap), maar hij lijkt niet getest of niet compatibel te zijn vanaf 4.8.4. Kan hier uitsluitsel over gegeven worden? Kan ik de plugin veilig updaten of kan ik beter naar een tussen-release?

Thanks!

**Comment by mdeheij** [comment]
Hi! Goed om te horen dat de plugin bevalt!
Je kunt de plugin gerust updaten naar de laatste versie en bij twijfel kun je ook altijd e-mails testen vanuit de plugin zelf. Ik heb zojuist voor je de nieuwste versie van WordPress getest en dit ook in de plugin aangepast.
